In [4]:
import csv
import pandas as pd

In [6]:
df = pd.read_csv('https://stats.idre.ucla.edu/stat/data/hsbdemo.csv')

In [7]:
df

,id,female,ses,schtyp,prog,read,write,math,science,socst,honors,awards,cid
0,45,female,low,public,vocation,34,35,41,29,26,not enrolled,0,1
1,108,male,middle,public,general,34,33,41,36,36,not enrolled,0,1
2,15,male,high,public,vocation,39,39,44,26,42,not enrolled,0,1
3,67,male,low,public,vocation,37,37,42,33,32,not enrolled,0,1
4,153,male,middle,public,vocation,39,31,40,39,51,not enrolled,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,100,female,high,public,academic,63,65,71,69,71,enrolled,5,20
196,143,male,middle,public,vocation,63,63,75,72,66,enrolled,4,20
197,68,male,middle,public,academic,73,67,71,63,66,enrolled,7,20
198,57,female,middle,public,academic,71,65,72,66,56,enrolled,5,20
199,132,male,middle,public,academic,73,62,73,69,66,enrolled,3,20

In [8]:
df.write.sum()

10555

In [38]:
df1 = df.groupby(['prog']).mean()

In [41]:
df1 = df.groupby(['prog']).mean()
index_list = list(df1.index)
new_index = []
for i in index_list:
    new_index.append(i+"_mean")
new_index
df_2 = df1.rename(index= (dict(zip(index_list, new_index))))

In [25]:
new_index

['academic_mean', 'general_mean', 'vocation_mean']

In [26]:
index_iterator = zip(index_list, new_index)
index_dict = dict(index_iterator)

In [29]:
index_dict = dict(zip(index_list, new_index))

In [32]:
df_2 = df1.rename(index= (dict(zip(index_list, new_index))))

In [33]:
df_2

,id,read,write,math,science,socst,awards,cid
prog,,,,,,,,
academic_mean,107.628571,56.161905,56.257143,56.733333,53.800000,56.695238,2.247619,12.771429
general_mean,97.311111,49.755556,51.333333,50.022222,52.444444,50.600000,1.333333,9.400000
vocation_mean,88.400000,46.200000,46.760000,46.420000,47.220000,45.020000,0.760000,6.440000